name:                verigraph-GUI
version:             0.2.0.4
github:              "artFuchs/verigraph-GUI"
license:             Apache-2.0
author:              "Arthur Lucena Fuchs"
maintainer:          "alfuchs@inf.ufrgs.br"
copyright:           "2019-2021 Arthur Lucena Fuchs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/artFuchs/graph-editor#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk
- gi-gdk
- gi-glib
- prettyprinter
- text
- cairo
- pango
- gi-cairo
- gi-pango
- haskell-gi-base
- transformers
- parallel
- containers
- set-monad
- hxt
- mtl
- filepath
- parsec
- directory
- optparse-applicative
- matrix
- random
- split
- time

library:
  source-dirs: src

executables:
  verigraph-GUI:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - verigraph-GUI

benchmarks:
  modelchecker-benchmark:
    main:             ModelChecker.hs
    source-dirs:      benchmark
    dependencies:
    - verigraph-GUI
    - tasty-bench
  statespace-benchmark:
    main:             StateSpace.hs
    source-dirs:      benchmark
    dependencies:
      - verigraph-GUI
      - tasty-bench
